# Dockerfile generated by GeneXus (C#)
##FROM genexus/dotnet:4.6.2
FROM mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
LABEL maintainer="ArturoRodeaVictoria <ArturoRodeaVictoria@example.com>"
WORKDIR c:/inetpub/wwwroot/
COPY ["temp/", "c:/inetpub/wwwroot/"]
