# Dockerfile generated by GeneXus (C#)
FROM genexus/dotnet:4.6.2
LABEL maintainer="ArturoRodeaVictoria <ArturoRodeaVictoria@example.com>"
WORKDIR c:/inetpub/wwwroot/
COPY ["temp/", "c:/inetpub/wwwroot/"]
