name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
        login-server: azcrhs.azurecr.io
        username: azcrhs
        password: dO8g7Il/12Qs2rDRGoxchLSBo8GUJjwE6yL+wZlOAw+ACRBciYKr
    - name: Build and push the Docker image
      run: |
        docker build . --file Dockerfile --tag azcrhs.azurecr.io/setuppredictivows:${{github.run_number}}
        docker push azcrhs.azurecr.io/setuppredictivows:${{github.run_number}}

    
